# Ports are host:container
services:
  reverse-proxy:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - frontend
      - api
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    networks:
      - main

  ### Auth service
  api:
    build:
      context: ./api
      target: dev
    command: sh -c "python main.py"
    volumes:
      - ./api/src:/app
      - /app/venv
    env_file:
      - .env.dev
    networks:
      - main
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env.dev
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - main
    ports:
      - "5432:5432"
  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NEXT_WEBPACK_USEPOLLING=1
      - WATCHPACK_POLLING=true
    command: sh -c "npm i && npm run dev"
    depends_on:
      - api
    networks:
      - main

networks:
  main:
    driver: bridge
volumes:
  frontend_node_modules:
